<Project>
  <PropertyGroup Condition="'$(MSBuildProjectName)' == 'Trophy.Catalogue'">
    <StartupObject>Trophy.Catalogue.EntryPoint</StartupObject>
  </PropertyGroup>
  <ItemGroup Condition="'$(MSBuildProjectName)' == 'Trophy.Catalogue'">
    <Compile Remove="Program.cs" />
  </ItemGroup>
</Project>
