// Run only against an explicitly isolated local QA server. See LAUNCH-RUNBOOK.md.
const { chromium, request } = require(process.env.PLAYWRIGHT_MODULE || 'playwright');
const fs = require('node:fs');
const path = require('node:path');
const assert = require('node:assert/strict');
const base = process.env.QA_BASE_URL || 'http://127.0.0.1:5192';
const dataRoot = process.env.QA_DATA_PATH;
const output = process.env.QA_OUTPUT_PATH;
if (new URL(base).hostname !== '127.0.0.1' || !dataRoot || !path.basename(dataRoot).startsWith('trophy-launch-qa-') || !output) throw Error('An isolated local QA_DATA_PATH and QA_OUTPUT_PATH are required.');
const password = 'FixturePassword123!';
const serial = Date.now();
const email = `owner-${serial}@archive.example`;
const checks = [];
const ok = text => { checks.push(text); console.log('PASS ' + text); };
(async () => {
  fs.mkdirSync(output, { recursive: true });
  const owner = await request.newContext({ baseURL: base, extraHTTPHeaders: { Origin: base } });
  const anon = await request.newContext({ baseURL: base });
  async function api(client, route, method = 'GET', data) {
    const response = await client.fetch(route, { method, ...(data === undefined ? {} : { data }) });
    assert(response.ok(), `${method} ${route}: ${response.status()} ${await response.text()}`);
    return response.status() === 204 ? null : response.json();
  }
  const auth = await api(owner, '/api/auth/signup', 'POST', { displayName: 'Launch QA owner', email, password });
  assert.equal(auth.user.emailVerified, false); assert.equal(auth.verificationEmailSent, true);
  const mail = fs.readdirSync(path.join(dataRoot, 'mail')).map(name => fs.readFileSync(path.join(dataRoot, 'mail', name), 'utf8')).find(text => text.includes(email));
  assert(mail, 'Development verification email exists');
  const normalized = mail.replace(/=\r?\n/g, '').replace(/=3D/g, '=');
  const token = normalized.match(/#verify=([A-Za-z0-9_-]+)/)?.[1]; assert(token, 'Verification token found');
  await api(owner, '/api/auth/verify-email', 'POST', { token });
  const replay = await owner.post('/api/auth/verify-email', { data: { token } }); assert.equal(replay.status(), 400);
  ok('Signup, local verification email and single-use verification');
  await api(owner, '/api/club', 'PUT', { name: 'Launch QA Golf Club', sport: 'Golf', country: 'United Kingdom', website: 'https://club.example' });
  const png = Buffer.from('iVBORw0KGgoAAAANSUhEUgAAAAEAAAABCAQAAAC1HAwCAAAAC0lEQVR42mP8/x8AAwMCAO+jx0sAAAAASUVORK5CYII=', 'base64');
  const logo = await owner.post('/api/club/logo', { multipart: { logo: { name: 'fixture.png', mimeType: 'image/png', buffer: png } } }); assert(logo.ok());
  const signed = await api(owner, '/api/auth/status'); const clubId = signed.club.id;
  const created = await api(owner, '/api/trophies', 'POST', { name: 'Launch QA Cup', code: 'QA1', category: 'Club competitions' }); const trophyId = created.trophy.id;
  await api(owner, `/api/trophies/${trophyId}/winners`, 'POST', { year: 2024, name: 'J. Fixture', reviewState: 'confirmed', description: 'PRIVATE DESCRIPTION' });
  assert.equal((await anon.get(`/api/public/clubs/${clubId}/honours`)).status(), 404);
  assert.equal((await anon.get('/api/trophies')).status(), 401);
  assert.equal((await anon.post('/api/trophies', { data: { name: 'Attack' }, headers: { Origin: 'https://attacker.example' } })).status(), 403);
  ok('Archive starts private and rejects unauthenticated or cross-origin writes');
  const publication = await api(owner, '/api/publication'); const options = { namePolicy: 'inscription', includeDescriptions: false, includeJuniorTrophies: false, selectedWinnerKeys: publication.candidates.map(item => item.key), allowedEmbedOrigins: ['https://club.example'] };
  const preview = await api(owner, '/api/publication/preview', 'POST', options);
  assert(!JSON.stringify(preview.snapshot).includes('PRIVATE DESCRIPTION'));
  await api(owner, '/api/publication/publish', 'POST', { options, previewFingerprint: preview.fingerprint, publicationApproved: true });
  const board = await api(anon, `/api/public/clubs/${clubId}/honours`); assert.equal(board.summary.honours, 1);
  assert((await anon.get(`/embed/${clubId}`)).headers()['content-security-policy'].includes('https://club.example'));
  ok('Reviewed publication exposes only selected public fields with controlled embed origins');
  const billing = await api(owner, '/api/billing'); assert.equal(billing.balance.available, 1); assert.equal(billing.paymentsEnabled, false);
  assert.equal((await owner.post('/api/billing/checkout', { data: { packCode: 'club', requestId: crypto.randomUUID() } })).status(), 503);
  ok('Server balance is real and unconfigured checkout cannot take payments');
  const second = await request.newContext({ baseURL: base, extraHTTPHeaders: { Origin: base } });
  await api(second, '/api/auth/signup', 'POST', { displayName: 'Separate QA owner', email: `separate-${serial}@archive.example`, password });
  await api(second, '/api/club', 'PUT', { name: 'Separate QA club', sport: 'Golf', country: 'United Kingdom' });
  assert((await second.post('/api/club/logo', { multipart: { logo: { name: 'fixture.png', mimeType: 'image/png', buffer: png } } })).ok());
  assert.equal((await second.get(`/api/trophies/${trophyId}`)).status(), 404);
  assert.equal((await api(second, '/api/trophies')).items.length, 0);
  assert.equal((await api(second, '/api/billing')).balance.available, 1);
  await second.dispose(); ok('A separate club cannot read the original club trophy or share its balance');
  const browser = await chromium.launch({ headless: true, channel: 'msedge' });
  const context = await browser.newContext({ storageState: await owner.storageState(), viewport: { width: 1440, height: 1100 } });
  const page = await context.newPage(); const errors = [];
  page.on('pageerror', error => errors.push(error.message));
  await page.goto(base + '/archive.html'); await page.locator('#login-screen').waitFor({ state: 'hidden' });
  await page.locator('#honours-board-link').click(); await page.locator('#publication-state').filter({ hasText: 'Public' }).waitFor();
  assert(await page.locator('#publication-dialog').evaluate(element => element.getBoundingClientRect().width > 1000), 'Desktop publication preview has a usable width');
  await page.locator('#publication-controls summary').click(); await page.locator('#publication-preview-button').click();
  await page.frameLocator('#publication-preview-frame').getByText('J. Fixture', { exact: true }).first().waitFor();
  await page.screenshot({ path: path.join(output, 'publication-desktop.png'), fullPage: true });
  await page.locator('#publication-dialog .commercial-dialog-close').click(); await page.locator('#header-plan-button').click();
  await page.getByText('1 trophy credit available', { exact: true }).waitFor(); await page.screenshot({ path: path.join(output, 'billing-desktop.png'), fullPage: true });
  await page.locator('#plan-dialog .commercial-dialog-close').click();
  await page.goto(base + '/account-security.html#settings'); await page.getByRole('heading', { name: /security/i }).first().waitFor();
  await page.screenshot({ path: path.join(output, 'security-desktop.png'), fullPage: true });
  await page.setViewportSize({ width: 390, height: 844 }); await page.goto(base + '/archive.html'); await page.locator('#login-screen').waitFor({ state: 'hidden' });
  await page.locator('#honours-board-link').click(); await page.locator('#publication-controls summary').click();
  assert(await page.evaluate(() => document.documentElement.scrollWidth <= innerWidth + 1), 'No mobile horizontal page overflow');
  await page.screenshot({ path: path.join(output, 'publication-mobile.png'), fullPage: true });
  assert.deepEqual(errors, []); ok('Desktop and mobile publication, private preview, billing and security screens have no JavaScript errors');
  await api(owner, '/api/publication/withdraw', 'POST', {}); assert.equal((await anon.get(`/api/public/clubs/${clubId}/honours`)).status(), 404);
  assert.equal((await anon.get(`/honours/${clubId}`)).status(), 404); assert.equal((await anon.get(`/embed/${clubId}`)).status(), 404);
  assert.equal((await api(owner, `/api/trophies/${trophyId}`)).trophy.winners.length, 1); ok('Withdrawal removes public access while retaining the private trophy record');
  await api(owner, '/api/auth/forgot-password', 'POST', { email });
  const resetMail = fs.readdirSync(path.join(dataRoot, 'mail')).map(name => fs.readFileSync(path.join(dataRoot, 'mail', name), 'utf8')).find(text => text.includes(email) && text.includes('Reset your Trophy Archive password'));
  const resetToken = resetMail.replace(/=\r?\n/g, '').replace(/=3D/g, '=').match(/#reset=([A-Za-z0-9_-]+)/)?.[1]; assert(resetToken);
  await page.goto(base + '/account-security.html#reset=' + resetToken);
  await page.getByLabel('New password', { exact: true }).fill('ReplacementPassword456!');
  await page.getByLabel('Confirm new password', { exact: true }).fill('ReplacementPassword456!');
  assert(!page.url().includes(resetToken), 'Reset token is removed from browser URL');
  await page.getByRole('button', { name: 'Save new password' }).click();
  await page.getByText(/Password changed/).waitFor();
  assert.equal((await owner.get('/api/trophies')).status(), 401);
  assert.equal((await owner.post('/api/auth/reset-password', { data: { token: resetToken, password: 'ReplacementPassword789!' } })).status(), 400);
  ok('Password reset scrubs its token, revokes an existing session and rejects replay');
  await context.close(); await browser.close(); await owner.dispose(); await anon.dispose();
  fs.writeFileSync(path.join(output, 'smoke-results.json'), JSON.stringify({ checks, completedAt: new Date().toISOString() }, null, 2));
})().catch(error => { console.error(error); process.exit(1); });
