// Run only against an explicitly isolated local QA server. See LAUNCH-RUNBOOK.md.
const { chromium, request } = require(process.env.PLAYWRIGHT_MODULE || 'playwright');
const fs = require('node:fs');
const path = require('node:path');
const assert = require('node:assert/strict');
const base = process.env.QA_BASE_URL || 'http://127.0.0.1:5192';
const dataRoot = process.env.QA_DATA_PATH;
const output = process.env.QA_OUTPUT_PATH;
if (new URL(base).hostname !== '127.0.0.1' || !dataRoot || !path.basename(dataRoot).startsWith('trophy-launch-qa-') || !output) throw Error('An isolated local QA_DATA_PATH and QA_OUTPUT_PATH are required.');
const password = 'FixturePassword123!';
const serial = Date.now();
const email = `owner-${serial}@archive.example`;
const checks = [];
const ok = text => { checks.push(text); console.log('PASS ' + text); };
(async () => {
  fs.mkdirSync(output, { recursive: true });
  const owner = await request.newContext({ baseURL: base, extraHTTPHeaders: { Origin: base } });
  const anon = await request.newContext({ baseURL: base });
  async function api(client, route, method = 'GET', data) {
    const response = await client.fetch(route, { method, ...(data === undefined ? {} : { data }) });
    assert(response.ok(), `${method} ${route}: ${response.status()} ${await response.text()}`);
    return response.status() === 204 ? null : response.json();
  }
  const auth = await api(owner, '/api/auth/signup', 'POST', { displayName: 'Launch QA owner', email, password });
  assert.equal(auth.user.emailVerified, false); assert.equal(auth.verificationEmailSent, true);
  const mail = fs.readdirSync(path.join(dataRoot, 'mail')).map(name => fs.readFileSync(path.join(dataRoot, 'mail', name), 'utf8')).find(text => text.includes(email));
  assert(mail, 'Development verification email exists');
  const normalized = mail.replace(/=\r?\n/g, '').replace(/=3D/g, '=');
  const token = normalized.match(/#verify=([A-Za-z0-9_-]+)/)?.[1]; assert(token, 'Verification token found');
  await api(owner, '/api/auth/verify-email', 'POST', { token });
  const replay = await owner.post('/api/auth/verify-email', { data: { token } }); assert.equal(replay.status(), 400);
  ok('Signup, local verification email and single-use verification');
  await api(owner, '/api/club', 'PUT', { name: 'Launch QA Golf Club', sport: 'Golf', country: 'United Kingdom', website: 'https://club.example' });
  const png = Buffer.from('iVBORw0KGgoAAAANSUhEUgAAAAEAAAABCAQAAAC1HAwCAAAAC0lEQVR42mP8/x8AAwMCAO+jx0sAAAAASUVORK5CYII=', 'base64');
  const logo = await owner.post('/api/club/logo', { multipart: { logo: { name: 'fixture.png', mimeType: 'image/png', buffer: png } } }); assert(logo.ok());
  const signed = await api(owner, '/api/auth/status'); const clubId = signed.club.id;
  const created = await api(owner, '/api/trophies', 'POST', { name: 'Launch QA Cup', code: 'QA1', category: 'Club competitions' }); const trophyId = created.trophy.id;
  await api(owner, `/api/trophies/${trophyId}/winners`, 'POST', { year: 2024, name: 'J. Fixture', reviewState: 'confirmed', description: 'PRIVATE DESCRIPTION' });
  assert.equal((await anon.get(`/api/public/clubs/${clubId}/honours`)).status(), 404);
  assert.equal((await anon.get('/api/trophies')).status(), 401);
  assert.equal((await anon.post('/api/trophies', { data: { name: 'Attack' }, headers: { Origin: 'https://attacker.example' } })).status(), 403);
  ok('Archive starts private and rejects unauthenticated or cross-origin writes');

  const browser = await chromium.launch({ headless: true, channel: 'msedge' });
  const context = await browser.newContext({ storageState: await owner.storageState(), viewport: { width: 1440, height: 1100 } });
  const page = await context.newPage(); const errors = [];
  page.on('pageerror', error => errors.push(error.message));
  await page.goto(base + '/archive.html');
  await page.locator('#login-screen').waitFor({ state: 'hidden' });
  await page.locator('#honours-board-link').click();
  await page.frameLocator('#publication-preview-frame').getByText('J. Fixture', { exact: true }).first().waitFor();
  assert.equal(await page.locator('#publication-controls').getAttribute('open'), null);
  assert.equal(await page.locator('#publication-approved').count(), 0);
  assert.equal((await anon.get('/honours/' + clubId)).status(), 404);
  assert(await page.locator('#publication-publish').isEnabled());
  await page.screenshot({ path: path.join(output, 'board-preview-desktop.png'), fullPage: true });
  ok('Opening honours board renders confirmed winners automatically, without reconfirmation or publication');
  await page.locator('#publication-publish').click();
  await page.locator('#publication-sharing').waitFor({ state: 'visible' });
  const publicUrl = await page.locator('#publication-link').inputValue();
  assert.equal(publicUrl, base + '/honours/' + clubId);
  assert.equal((await anon.get(publicUrl)).status(), 200);
  const board = await api(anon, '/api/public/clubs/' + clubId + '/honours');
  assert.equal(board.summary.honours, 1);
  assert(!JSON.stringify(board).includes('PRIVATE DESCRIPTION'));
  await page.screenshot({ path: path.join(output, 'board-published-desktop.png'), fullPage: true });
  ok('One explicit Publish action produces a working public URL with only the chosen public fields');
  await page.locator('#publication-dialog .commercial-dialog-close').click();
  await page.setViewportSize({ width: 390, height: 844 });
  await page.locator('#honours-board-link').click();
  await page.frameLocator('#publication-preview-frame').getByText('J. Fixture', { exact: true }).first().waitFor();
  assert.equal(await page.locator('#publication-publish').textContent(), 'Publish updates');
  assert(await page.evaluate(() => document.documentElement.scrollWidth <= innerWidth + 1));
  await page.screenshot({ path: path.join(output, 'board-preview-mobile.png'), fullPage: true });
  await page.locator('#publication-controls summary').click();
  await page.locator('#publication-clear-visible').click();
  assert(await page.locator('#publication-publish').isDisabled());
  assert(await page.locator('#publication-preview-button').isDisabled());
  await page.locator('#publication-select-visible').click();
  await page.locator('#publication-preview-button').click();
  await page.frameLocator('#publication-preview-frame').getByText('J. Fixture', { exact: true }).first().waitFor();
  assert(await page.locator('#publication-publish').isEnabled());
  ok('Mobile layout fits and selection edits require a fresh preview before publication');
  await page.locator('#publication-withdraw').click();
  await page.locator('#publication-state').filter({ hasText: 'Private' }).waitFor();
  assert.equal((await anon.get(publicUrl)).status(), 404);
  assert.equal((await api(owner, '/api/trophies/' + trophyId)).trophy.winners.length, 1);
  assert.deepEqual(errors, []);
  ok('Withdrawal hides the public board and preserves the confirmed archive');
  await browser.close(); await owner.dispose(); await anon.dispose();
  fs.writeFileSync(path.join(output, 'board-flow-results.json'), JSON.stringify({ checks }, null, 2));
})().catch(error => { console.error(error); process.exit(1); });
